server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/kutuphane
    username: postgres
    password: asd123asd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  key: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e


